services:
  postgres-db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=megachollos
      - POSTGRES_PASSWORD=megachollos
      - POSTGRES_DB=megachollos
    ports:
      - "5432:5432"
