logging:
  level:
    com.megachollos: DEBUG

server:
  port: 8080
spring:
  elasticsearch:
    uris: http://localhost:9200
  datasource:
    url: jdbc:postgresql://localhost:5432/megachollos
    username: megachollos
    password: megachollos
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  liquibase:
    enabled: true
    database-change-log-lock-table: MEGACHOLLOS_CHANGELOGLOCK
    database-change-log-table: MEGACHOLLOS_CHANGELOG
  cache:
    type: none

core:
  swagger:
    server:
      url: http://localhost:${server.port}
      description: Local Server
  logstash:
    url: localhost:5044

megachollos:
  elasticsearch:
    index: megachollos-productos
