CREATE TABLE BRANDS
(
    UNIQUE_NAME        VARCHAR(255),
    DISPLAY_NAME       VARCHAR(255)   NOT NULL,

    CONSTRAINT PK_BRANDS PRIMARY KEY (UNIQUE_NAME)
);

CREATE TABLE CATEGORIES
(
    UNIQUE_NAME        VARCHAR(255),
    DISPLAY_NAME       VARCHAR(255)   NOT NULL,
    PARENT_CATEGORY    VARCHAR(255),

    CONSTRAINT PK_CATEGORIES PRIMARY KEY (UNIQUE_NAME),
    CONSTRAINT FK_CATEGORIES_CATEGORIES_UNIQUE_NAME FOREIGN KEY (PARENT_CATEGORY) REFERENCES CATEGORIES (UNIQUE_NAME)
);

CREATE TABLE MODELS
(
    ID                 BIGINT,
    DISPLAY_NAME       VARCHAR(255) NOT NULL,
    CATEGORY           VARCHAR(255) NOT NULL,
    BRAND              VARCHAR(255) NOT NULL,

    CONSTRAINT PK_MODELS PRIMARY KEY (ID),
    CONSTRAINT FK_MODELS_CATEGORIES_UNIQUE_NAME FOREIGN KEY (CATEGORY) REFERENCES CATEGORIES (UNIQUE_NAME),
    CONSTRAINT FK_MODELS_BRANDS_UNIQUE_NAME FOREIGN KEY (BRAND) REFERENCES BRANDS (UNIQUE_NAME)
);

